-- Keep shared extensions installed during rollback.
-- This makes full rollback idempotent across CI and managed Postgres instances
-- where extension removal can be restricted or fail despite schema teardown.
