DROP POLICY IF EXISTS trip_memberships_select_self ON trip_memberships;
DROP POLICY IF EXISTS user_preferences_select_self ON user_preferences;
DROP POLICY IF EXISTS notifications_select_self ON notifications;
DROP POLICY IF EXISTS expenses_select_trip_member ON expenses;
DROP POLICY IF EXISTS trips_select_member ON trips;

DROP POLICY IF EXISTS fcm_tokens_service_role_all ON fcm_tokens;
DROP POLICY IF EXISTS audit_logs_service_role_all ON audit_logs;
DROP POLICY IF EXISTS outbox_events_service_role_all ON outbox_events;
DROP POLICY IF EXISTS share_links_service_role_all ON share_links;
DROP POLICY IF EXISTS notifications_service_role_all ON notifications;
DROP POLICY IF EXISTS ai_plan_validation_results_service_role_all ON ai_plan_validation_results;
DROP POLICY IF EXISTS ai_plan_drafts_service_role_all ON ai_plan_drafts;
DROP POLICY IF EXISTS ai_plan_requests_service_role_all ON ai_plan_requests;
DROP POLICY IF EXISTS expenses_service_role_all ON expenses;
DROP POLICY IF EXISTS budget_profiles_service_role_all ON budget_profiles;
DROP POLICY IF EXISTS trip_idempotency_keys_service_role_all ON trip_idempotency_keys;
DROP POLICY IF EXISTS itinerary_items_service_role_all ON itinerary_items;
DROP POLICY IF EXISTS route_snapshots_service_role_all ON route_snapshots;
DROP POLICY IF EXISTS place_snapshots_service_role_all ON place_snapshots;
DROP POLICY IF EXISTS itinerary_days_service_role_all ON itinerary_days;
DROP POLICY IF EXISTS trip_invitations_service_role_all ON trip_invitations;
DROP POLICY IF EXISTS trip_memberships_service_role_all ON trip_memberships;
DROP POLICY IF EXISTS trips_service_role_all ON trips;
DROP POLICY IF EXISTS sessions_service_role_all ON sessions;
DROP POLICY IF EXISTS llm_provider_configs_service_role_all ON llm_provider_configs;
DROP POLICY IF EXISTS user_preferences_service_role_all ON user_preferences;
DROP POLICY IF EXISTS users_service_role_all ON users;

ALTER TABLE fcm_tokens DISABLE ROW LEVEL SECURITY;
ALTER TABLE audit_logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE outbox_events DISABLE ROW LEVEL SECURITY;
ALTER TABLE share_links DISABLE ROW LEVEL SECURITY;
ALTER TABLE notifications DISABLE ROW LEVEL SECURITY;
ALTER TABLE ai_plan_validation_results DISABLE ROW LEVEL SECURITY;
ALTER TABLE ai_plan_drafts DISABLE ROW LEVEL SECURITY;
ALTER TABLE ai_plan_requests DISABLE ROW LEVEL SECURITY;
ALTER TABLE expenses DISABLE ROW LEVEL SECURITY;
ALTER TABLE budget_profiles DISABLE ROW LEVEL SECURITY;
ALTER TABLE trip_idempotency_keys DISABLE ROW LEVEL SECURITY;
ALTER TABLE itinerary_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE route_snapshots DISABLE ROW LEVEL SECURITY;
ALTER TABLE place_snapshots DISABLE ROW LEVEL SECURITY;
ALTER TABLE itinerary_days DISABLE ROW LEVEL SECURITY;
ALTER TABLE trip_invitations DISABLE ROW LEVEL SECURITY;
ALTER TABLE trip_memberships DISABLE ROW LEVEL SECURITY;
ALTER TABLE trips DISABLE ROW LEVEL SECURITY;
ALTER TABLE sessions DISABLE ROW LEVEL SECURITY;
ALTER TABLE llm_provider_configs DISABLE ROW LEVEL SECURITY;
ALTER TABLE user_preferences DISABLE ROW LEVEL SECURITY;
ALTER TABLE users DISABLE ROW LEVEL SECURITY;

DROP FUNCTION IF EXISTS public.app_is_service_role();
DROP FUNCTION IF EXISTS public.app_uid();
