package errors

const (
	CodeBadRequest              = "BAD_REQUEST"
	CodeConflict                = "CONFLICT"
	CodeServiceUnavailable      = "SERVICE_UNAVAILABLE"
	CodeUnauthorized            = "AUTH_UNAUTHORIZED"
	CodeForbidden               = "AUTH_FORBIDDEN"
	CodeNotFound                = "NOT_FOUND"
	CodeTripNotFound            = "TRIP_NOT_FOUND"
	CodeVersionConflict         = "TRIP_VERSION_CONFLICT"
	CodeTimeConflict            = "ITINERARY_TIME_CONFLICT"
	CodeInvalidDateRange        = "ITINERARY_INVALID_DATE_RANGE"
	CodeBudgetCurrency          = "BUDGET_INVALID_CURRENCY"
	CodeBudgetRateUnavailable   = "BUDGET_RATE_UNAVAILABLE"
	CodeMapProviderTimeout      = "MAP_PROVIDER_TIMEOUT"
	CodeMapProviderQuotaExceed  = "MAP_PROVIDER_QUOTA_EXCEEDED"
	CodeAIProviderTimeout       = "AI_PROVIDER_TIMEOUT"
	CodeAIProviderInvalidOutput = "AI_PROVIDER_INVALID_OUTPUT"
	CodeAIProviderAuthFailed    = "AI_PROVIDER_AUTH_FAILED"
	CodeAIProviderQuotaExceed   = "AI_PROVIDER_QUOTA_EXCEEDED"
	CodeAIProviderBadRequest    = "AI_PROVIDER_BAD_REQUEST"
	CodeAIProviderUnavailable   = "AI_PROVIDER_UNAVAILABLE"
	CodeAIProviderCircuitOpen   = "AI_PROVIDER_CIRCUIT_OPEN"
	CodeAIDraftInvalid          = "AI_DRAFT_INVALID"
	CodeRateLimitExceeded       = "RATE_LIMIT_EXCEEDED"
	CodeCSRFInvalid             = "CSRF_INVALID"
	CodeInternalError           = "INTERNAL_ERROR"
	CodeNotImplemented          = "NOT_IMPLEMENTED"
	CodeAdminForbidden          = "ADMIN_FORBIDDEN"
)
