#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
BACKEND_ENV_FILE="${ROOT_DIR}/.env.supabase.local"
WEB_ENV_FILE="${ROOT_DIR}/apps/web/.env.supabase.local"

require_command() {
  local cmd="$1"
  if ! command -v "$cmd" >/dev/null 2>&1; then
    echo "missing required command: ${cmd}" >&2
    exit 1
  fi
}

extract_env_value() {
  local env_dump="$1"
  local key="$2"
  local line
  line="$(printf '%s\n' "$env_dump" | awk -F= -v k="$key" '$1==k {print substr($0, index($0,$2)); exit}')"
  printf '%s' "$line"
}

fallback_first_non_empty() {
  for value in "$@"; do
    if [[ -n "$value" ]]; then
      printf '%s' "$value"
      return 0
    fi
  done
  printf ''
}

require_command supabase

cd "$ROOT_DIR"
echo "starting supabase local stack..."
supabase start >/dev/null

echo "reading supabase runtime variables..."
status_env="$(supabase status -o env)"
if [[ -z "$status_env" ]]; then
  echo "failed to read supabase env output (supabase status -o env)" >&2
  exit 1
fi

api_url="$(extract_env_value "$status_env" "API_URL")"
anon_key="$(extract_env_value "$status_env" "ANON_KEY")"
service_role_key="$(extract_env_value "$status_env" "SERVICE_ROLE_KEY")"

db_port="$(fallback_first_non_empty \
  "$(extract_env_value "$status_env" "DB_PORT")" \
  "$(extract_env_value "$status_env" "POSTGRES_PORT")" \
  "54322")"
db_user="$(fallback_first_non_empty \
  "$(extract_env_value "$status_env" "DB_USER")" \
  "$(extract_env_value "$status_env" "POSTGRES_USER")" \
  "postgres")"
db_password="$(fallback_first_non_empty \
  "$(extract_env_value "$status_env" "DB_PASSWORD")" \
  "$(extract_env_value "$status_env" "POSTGRES_PASSWORD")" \
  "postgres")"
db_name="$(fallback_first_non_empty \
  "$(extract_env_value "$status_env" "DB_NAME")" \
  "$(extract_env_value "$status_env" "POSTGRES_DB")" \
  "postgres")"

if [[ -z "$api_url" || -z "$anon_key" || -z "$service_role_key" ]]; then
  echo "supabase status output is missing API_URL / ANON_KEY / SERVICE_ROLE_KEY" >&2
  echo "received output:" >&2
  printf '%s\n' "$status_env" >&2
  exit 1
fi

# Containers cannot reach host 127.0.0.1 directly; use host gateway alias.
compose_db_host="host.docker.internal"

cat >"$BACKEND_ENV_FILE" <<EOF
# Generated by scripts/supabase-local-start.sh
DB_HOST=${compose_db_host}
DB_PORT=${db_port}
DB_USER=${db_user}
DB_PASSWORD=${db_password}
DB_NAME=${db_name}
DB_SSLMODE=disable
MIGRATE_DATABASE_URL=postgresql://${db_user}:${db_password}@${compose_db_host}:${db_port}/${db_name}?sslmode=disable
SUPABASE_ANON_KEY=${anon_key}
SUPABASE_SERVICE_ROLE_KEY=${service_role_key}
EOF

cat >"$WEB_ENV_FILE" <<EOF
# Generated by scripts/supabase-local-start.sh
VITE_API_BASE_URL=http://localhost:8080
VITE_SUPABASE_URL=${api_url}
VITE_SUPABASE_ANON_KEY=${anon_key}
EOF

cat <<EOF
generated:
- ${BACKEND_ENV_FILE}
- ${WEB_ENV_FILE}

next steps:
1) run migrations:
   docker compose --env-file .env --env-file .env.supabase.local --profile tools run --rm migrate
2) run backend + web:
   docker compose --env-file .env --env-file .env.supabase.local up -d redis api worker web
3) if using vite dev:
   cp apps/web/.env.supabase.local apps/web/.env.local
EOF
